### PR TITLE
Added flag to allow views to relayout

### PR DESCRIPTION
**Pull request by PorterHoskins**

### CODE REVIEW

**Comment by hiltonc** [comment]
Why?

**Comment by PorterHoskins** [comment]
I need it for setting the page insets on the audio player for the iPad.

**Comment by PorterHoskins** [comment]
I can show you if you want to maybe help me come up with a different solution.

**Comment by hiltonc** [comment]
Yeah, show me. It seems a little hokey to do it this way.

**Comment by PorterHoskins** [comment]
As usual, you are correct. 😊

**Pull request closed without merging**
